Repository melvillewong/SSH, pull requests merged in 2024-12, with the labels that each got.

#2 Add about_git.md
  README.md
  about_git.md
Labels: documentation

#3 populate access_log and chores_log in ssh_smart_scheduling.sql
  ssh_smart_scheduling.sql
Labels: enhancement

#5 Create postgresql_tutorial.md
  postgresql_tutorial.md
Labels: documentation

#8 Update postgresql_tutorial.md
  postgresql_tutorial.md
Labels: documentation

#9 Set up PostgreSQL server with Docker
  .DS_Store
  .gitignore
  DockerFile
  README.md
  docker-compose.yml
  migrations/V1__initial_ssh_smart_scheduling.sql
  migrations/V2__add_events_table.sql
  migrations/V3__drop_events_table.sql
Labels: documentation, enhancement

#15 Update README.md
  README.md
Labels: documentation

#19 Add basic CI
  .github/workflows/java.yml
Labels: enhancement

#22 Organise documents and modify .gitignore
  .gitignore
  docs/README.md
  docs/about_git.md
  docs/postgresql_tutorial.md
Labels: documentation

#25 Add 'Modify your Commit' section in about_git.md
  docs/about_git.md
Labels: documentation

#29 Finished Feature/sql samples
  .DS_Store
  .gitignore
  about_sql_queries.md
  java-temp/.DS_Store
  java-temp/.idea/.gitignore
  java-temp/.idea/libraries/lib.xml
  java-temp/.idea/misc.xml
  java-temp/.idea/modules.xml
  java-temp/.idea/vcs.xml
  java-temp/Credentials.java
  java-temp/README.md
  java-temp/RecordsDatabaseServer.java
  java-temp/RecordsDatabaseService.java
  java-temp/TerminalRecordsClient.java
  java-temp/autorun_total_hour_suggestion.sql
  java-temp/java-temp.iml
  java-temp/lib/postgresql-42.6.0.jar
  java-temp/out/production/java-temp/.idea/.gitignore
  java-temp/out/production/java-temp/.idea/libraries/lib.xml
  java-temp/out/production/java-temp/.idea/misc.xml
  java-temp/out/production/java-temp/.idea/modules.xml
  java-temp/out/production/java-temp/.idea/vcs.xml
  java-temp/out/production/java-temp/Credentials.class
  java-temp/out/production/java-temp/README.md
  java-temp/out/production/java-temp/RecordsDatabaseServer.class
  java-temp/out/production/java-temp/RecordsDatabaseService.class
  java-temp/out/production/java-temp/TerminalRecordsClient.class
  java-temp/out/production/java-temp/autorun_total_hour_suggestion.sql
  java-temp/out/production/java-temp/java-temp.iml
  java-temp/out/production/java-temp/lib/postgresql-42.6.0.jar
  migrations/V1__initial_ssh_smart_scheduling.sql
  migrations/V2__add_events_table.sql
  migrations/V3__drop_events_table.sql
  start_all.sh
Labels: enhancement

#31 Removed excessive debug code within RecordsDatabaseService.java
  java-temp/RecordsDatabaseService.java
Labels: enhancement

#32 A slight modification of autorun_chore_hour_suggestion.sql
  out/production/SSH/out/production/autorun_chore_hour_suggestion.sql
Labels: documentation

#33 Modify service module for chore_hour_suggestion SQL script
  app/service/src/main/java/com/example/service/Service.java
  app/service/src/main/resources/autorun_chore_hour_suggestion.sql
Labels: enhancement

#36 Added some junit test for client and server, and cache for Github Actions
  .github/workflows/java.yml
  app/client/src/test/java/com/example/client/ClientTest.java
  app/common/src/main/resources/autorun_total_hour_suggestion.sql
  app/server/build.gradle.kts
  app/server/src/main/java/com/example/server/Server.java
  app/server/src/test/java/com/example/server/ServerTest.java
  app/service/build.gradle.kts
  app/service/src/main/java/com/example/service/Service.java
  app/service/src/test/java/com/example/service/ServiceTest.java
  build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#37 Update to README.md
  docs/README.md
Labels: documentation
